name: CI - Docker Build

on:
  push:
    branches:
      - main
      - 'feature*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test


  build-and-push:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref_name == 'main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/frontface-app
          # Main ág esetén "latest" tag
          TAG=latest
          docker build -t $IMAGE_NAME:$TAG .

      - name: Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/frontface-app
          TAG=latest
          docker push $IMAGE_NAME:$TAG
